services:
  postgres:
    image: postgres:16
    container_name: movie-reco-postgres
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_pass
      POSTGRES_DB: movie_reco_db
    ports:
      - "5433:5432"
    volumes:
      - movie_reco_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_user -d movie_reco_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  movie_reco_pgdata: