from __future__ import annotations

from sqlalchemy import text
from sqlalchemy.orm import Session


def get_user_cf_candidates(
    db: Session,
    user_id: int,
    limit: int = 50,
) -> list[dict]:
    """
    Reads retrained collaborative filtering candidates for a user.

    These are generated by scripts/generate_cf_candidates_from_model.py
    and stored in user_cf_candidates.
    """

    query = text("""
        SELECT
            ucf.user_id,
            ucf.movie_id,
            ucf.score AS retrained_cf_score,
            ucf.rank AS retrained_cf_rank,
            ucf.reason,
            ucf.model_version,
            ucf.generated_at,

            m.title,
            m.genres,
            m.overview,
            m.poster_path,
            m.director,
            m.keywords,
            m.release_date
        FROM user_cf_candidates ucf
        LEFT JOIN movies_enriched m
            ON ucf.movie_id = m.movieid
        WHERE ucf.user_id = :user_id
        ORDER BY ucf.rank ASC, ucf.score DESC
        LIMIT :limit
    """)

    rows = db.execute(
        query,
        {
            "user_id": user_id,
            "limit": limit,
        },
    ).mappings().all()

    candidates: list[dict] = []

    for row in rows:
        candidates.append(
            {
                "movie_id": int(row["movie_id"]),
                "movieId": int(row["movie_id"]),

                "title": row["title"],
                "genres": row["genres"],
                "overview": row["overview"],
                "poster": row["poster_path"],
                "poster_path": row["poster_path"],
                "director": row["director"],
                "keywords": row["keywords"],
                "release_date": row["release_date"],

                "retrained_cf_score": float(row["retrained_cf_score"]),
                "retrained_cf_rank": row["retrained_cf_rank"],
                "reason": row["reason"],
                "model_version": row["model_version"],
                "generated_at": row["generated_at"],

                "source": "retrained_cf",
            }
        )

    return candidates